name: Build APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Verify Gradle wrapper
      run: |
        echo "Checking android directory contents:"
        ls -la android/
        echo "Checking gradle wrapper directory:"
        ls -la android/gradle/wrapper/
        echo "Checking if gradlew exists and is executable:"
        ls -la android/gradlew
        
    - name: Make gradlew executable
      run: |
        chmod +x android/gradlew
        echo "Made gradlew executable"
        ls -la android/gradlew
      
    - name: Build APK
      run: |
        cd android
        echo "Current directory: $(pwd)"
        echo "Contents of android directory:"
        ls -la
        echo "Checking gradlew permissions:"
        ls -la gradlew
        echo "Running gradlew assembleRelease:"
        ./gradlew assembleRelease
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: shoplist-apk-${{ github.sha }}
        path: android/app/build/outputs/apk/release/app-release.apk
